/**
 * @module mosquittoPasswd
 * @description Produces a broker password-file entry from a plaintext secret,
 * using only Web Crypto so it runs inside a Convex action.
 *
 * This exists so a minted broker credential is never stored in plaintext. The
 * broker's password file holds a derived hash, not the secret, so generating
 * that hash here means the database holds exactly what the broker holds — a
 * verifier, useless for authenticating — while the plaintext exists only in the
 * mint response and the operator's browser memory. It matches the bar
 * `cmdMcpTokens` already sets by persisting only a digest.
 *
 * Format (`$7$`): PBKDF2-SHA512, iteration count and salt inline, both salt and
 * derived key base64 with padding:
 *
 *     <username>:$7$<iterations>$<salt_b64>$<hash_b64>
 *
 * These parameters are not a guess. They were read off a password file
 * generated by the broker's own tool and then reproduced byte-for-byte through
 * the Web Crypto path below; `tests/convex/mosquittoPasswd.test.ts` pins that
 * comparison against the captured vector. A silently wrong hash would fail
 * closed — every affected credential simply refused, with the broker's logs the
 * only evidence — which is the same shape of invisible failure this whole
 * change exists to remove, so it is pinned rather than trusted.
 *
 * @license GPL-3.0-only
 */

/** Iterations the broker's own tool writes. Carried inline in every entry. */
export const MOSQUITTO_PBKDF2_ITERATIONS = 1000;
/** Salt length the broker's own tool writes, in bytes. */
export const MOSQUITTO_SALT_BYTES = 64;
/** Derived-key length, in bytes. SHA-512's natural output. */
export const MOSQUITTO_HASH_BYTES = 64;

/** Standard base64, with padding — the broker's format keeps the padding. */
function toBase64(bytes: Uint8Array): string {
  let bin = "";
  for (const b of bytes) bin += String.fromCharCode(b);
  return btoa(bin);
}

function fromBase64(value: string): Uint8Array {
  const bin = atob(value);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}

/** Derive the password verifier for a given secret and salt. */
export async function derivePbkdf2Sha512(
  password: string,
  salt: Uint8Array,
  iterations: number,
): Promise<Uint8Array> {
  const key = await crypto.subtle.importKey(
    "raw",
    new TextEncoder().encode(password),
    "PBKDF2",
    false,
    ["deriveBits"],
  );
  const bits = await crypto.subtle.deriveBits(
    // A fresh copy: some Web Crypto implementations reject a view over a
    // pooled buffer, and passing the caller's array through unchanged has no
    // benefit here.
    {
      name: "PBKDF2",
      salt: new Uint8Array(salt),
      iterations,
      hash: "SHA-512",
    },
    key,
    MOSQUITTO_HASH_BYTES * 8,
  );
  return new Uint8Array(bits);
}

/**
 * Build one password-file line for `username`. The salt is fresh per call, so
 * two entries for the same secret differ — which is the point.
 */
export async function buildPasswdEntry(
  username: string,
  password: string,
): Promise<string> {
  if (username.includes(":") || username.includes("\n")) {
    // The file is line- and colon-delimited, so a username carrying either
    // would forge a second entry. Refuse rather than emit a file whose meaning
    // differs from what the caller asked for.
    throw new Error("username may not contain ':' or a newline");
  }
  const salt = crypto.getRandomValues(new Uint8Array(MOSQUITTO_SALT_BYTES));
  const hash = await derivePbkdf2Sha512(
    password,
    salt,
    MOSQUITTO_PBKDF2_ITERATIONS,
  );
  return `${username}:$7$${MOSQUITTO_PBKDF2_ITERATIONS}$${toBase64(salt)}$${toBase64(hash)}`;
}

/**
 * Verify a plaintext against an entry produced by `buildPasswdEntry` (or by the
 * broker's own tool). Used by the tests to prove the two agree; not part of any
 * authentication path, because the broker is the only thing that authenticates.
 */
export async function verifyPasswdEntry(
  entry: string,
  password: string,
): Promise<boolean> {
  const colon = entry.indexOf(":");
  if (colon < 0) return false;
  const parts = entry.slice(colon + 1).split("$");
  // ["", "7", iterations, salt, hash]
  if (parts.length !== 5 || parts[1] !== "7") return false;
  const iterations = Number.parseInt(parts[2], 10);
  if (!Number.isFinite(iterations) || iterations <= 0) return false;

  const want = fromBase64(parts[4]);
  const got = await derivePbkdf2Sha512(password, fromBase64(parts[3]), iterations);
  if (got.length !== want.length) return false;
  // Constant-time compare. Not strictly required for a local test helper, but
  // leaving a variable-time comparison in a file about credentials invites it
  // being copied somewhere it does matter.
  let diff = 0;
  for (let i = 0; i < got.length; i++) diff |= got[i] ^ want[i];
  return diff === 0;
}
