/**
 * @module lib/atlas/msgpack
 * @description A reader-only MessagePack decoder, scoped to the shapes the Drone
 * Agent's Atlas wire contract actually emits. The agent frames every atlas
 * message as msgpack (`rmp_serde::to_vec_named`) and the GCS had no way to read
 * one, so the four `plugin.atlas.*` world-model descriptors were unreachable
 * from the browser.
 *
 * Decode only. Nothing in the GCS publishes on an atlas topic (the descriptors
 * are produced by a compute node and consumed here), so an encoder would be a
 * writer with no reader — and the byte fixtures the tests pin were generated by
 * the real Rust producer rather than by a local encoder, which is the whole
 * point of not having one.
 *
 * Two shapes this had to be built against rather than guessed, both confirmed
 * from producer output:
 *
 *  - **A struct is a map with `snake_case` string keys.** `to_vec_named` writes
 *    the Rust field names, so `session_id` / `gaussian_count` / `resolution_m`
 *    are the wire keys. An `Option::None` without `skip_serializing_if` is the
 *    key PRESENT carrying nil, not an absent key.
 *  - **`Vec<u8>` is an ARRAY of integers, not a `bin` payload.** `serde`
 *    serializes `Vec<u8>` as a sequence unless the field opts into
 *    `serde_bytes`, and `AtlasEvent::payload` does not, so a 216-byte payload
 *    crosses as `array16` of 216 ints (each byte over 0x7f as its own `uint8`).
 *    A decoder written against the obvious `bin8/16/32` assumption reads every
 *    real envelope as malformed. `bin` is still handled, so a producer that
 *    later adopts `serde_bytes` needs no change here.
 *
 * A 64-bit integer outside `Number.MAX_SAFE_INTEGER` decodes to `bigint` rather
 * than a silently-rounded `number`; the descriptor coercion narrows it. Ext,
 * timestamp and the reserved `0xc1` byte are rejected: the contract emits none
 * of them, so accepting them would mean inventing a reading.
 *
 * @license GPL-3.0-only
 */

/** A value decoded from msgpack. Maps decode to plain objects. */
export type MsgpackValue =
  | null
  | boolean
  | number
  | bigint
  | string
  | Uint8Array
  | MsgpackValue[]
  | { [key: string]: MsgpackValue };

/** A malformed, truncated, or out-of-contract msgpack frame. */
export class MsgpackError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "MsgpackError";
  }
}

const textDecoder =
  typeof TextDecoder !== "undefined" ? new TextDecoder("utf-8") : null;

class Reader {
  private readonly view: DataView;
  private offset = 0;

  constructor(private readonly bytes: Uint8Array) {
    this.view = new DataView(
      bytes.buffer,
      bytes.byteOffset,
      bytes.byteLength,
    );
  }

  get consumed(): number {
    return this.offset;
  }

  private need(n: number): number {
    const at = this.offset;
    if (at + n > this.bytes.byteLength) {
      throw new MsgpackError(
        `truncated frame: need ${n} byte(s) at offset ${at} of ${this.bytes.byteLength}`,
      );
    }
    this.offset = at + n;
    return at;
  }

  private u8(): number {
    return this.view.getUint8(this.need(1));
  }

  private u16(): number {
    return this.view.getUint16(this.need(2));
  }

  private u32(): number {
    return this.view.getUint32(this.need(4));
  }

  /** A 64-bit value, narrowed to `number` only when it is exactly
   * representable. Rounding a gaussian count would be a fabricated fact. */
  private big(signed: boolean): number | bigint {
    const at = this.need(8);
    const v = signed
      ? this.view.getBigInt64(at)
      : this.view.getBigUint64(at);
    return v >= BigInt(Number.MIN_SAFE_INTEGER) &&
      v <= BigInt(Number.MAX_SAFE_INTEGER)
      ? Number(v)
      : v;
  }

  private str(len: number): string {
    const at = this.need(len);
    const slice = this.bytes.subarray(at, at + len);
    if (textDecoder) return textDecoder.decode(slice);
    let out = "";
    for (const b of slice) out += String.fromCharCode(b);
    return out;
  }

  private bin(len: number): Uint8Array {
    const at = this.need(len);
    return this.bytes.slice(at, at + len);
  }

  private array(len: number): MsgpackValue[] {
    const out: MsgpackValue[] = new Array(len);
    for (let i = 0; i < len; i++) out[i] = this.value();
    return out;
  }

  private map(len: number): { [key: string]: MsgpackValue } {
    const out: { [key: string]: MsgpackValue } = {};
    for (let i = 0; i < len; i++) {
      const key = this.value();
      if (typeof key !== "string") {
        // Every struct the atlas contract emits is a string-keyed map. A
        // non-string key means this is not that contract, so refusing beats
        // coercing the key and pretending the frame parsed.
        throw new MsgpackError(
          `map key must be a string, got ${key === null ? "nil" : typeof key}`,
        );
      }
      out[key] = this.value();
    }
    return out;
  }

  value(): MsgpackValue {
    const tag = this.u8();
    // Fixed-range tags first: these are the overwhelming majority of bytes in a
    // descriptor (small ints, short keys, small maps).
    if (tag <= 0x7f) return tag; // positive fixint
    if (tag >= 0xe0) return tag - 0x100; // negative fixint
    if (tag >= 0x80 && tag <= 0x8f) return this.map(tag - 0x80); // fixmap
    if (tag >= 0x90 && tag <= 0x9f) return this.array(tag - 0x90); // fixarray
    if (tag >= 0xa0 && tag <= 0xbf) return this.str(tag - 0xa0); // fixstr

    switch (tag) {
      case 0xc0:
        return null;
      case 0xc2:
        return false;
      case 0xc3:
        return true;
      case 0xc4:
        return this.bin(this.u8());
      case 0xc5:
        return this.bin(this.u16());
      case 0xc6:
        return this.bin(this.u32());
      case 0xca:
        return this.view.getFloat32(this.need(4));
      case 0xcb:
        return this.view.getFloat64(this.need(8));
      case 0xcc:
        return this.u8();
      case 0xcd:
        return this.u16();
      case 0xce:
        return this.u32();
      case 0xcf:
        return this.big(false);
      case 0xd0:
        return this.view.getInt8(this.need(1));
      case 0xd1:
        return this.view.getInt16(this.need(2));
      case 0xd2:
        return this.view.getInt32(this.need(4));
      case 0xd3:
        return this.big(true);
      case 0xd9:
        return this.str(this.u8());
      case 0xda:
        return this.str(this.u16());
      case 0xdb:
        return this.str(this.u32());
      case 0xdc:
        return this.array(this.u16());
      case 0xdd:
        return this.array(this.u32());
      case 0xde:
        return this.map(this.u16());
      case 0xdf:
        return this.map(this.u32());
      default:
        throw new MsgpackError(
          `unsupported msgpack tag 0x${tag.toString(16).padStart(2, "0")}`,
        );
    }
  }
}

/**
 * Decode exactly one msgpack value from `bytes`.
 *
 * Trailing bytes are an error: one WebSocket frame carries one envelope, so a
 * frame with a second value appended is not the contract and reading only the
 * first value would silently accept a corrupt or concatenated stream.
 *
 * @throws {MsgpackError} on a truncated, trailing, or out-of-contract frame.
 */
export function decodeMsgpack(bytes: Uint8Array): MsgpackValue {
  const reader = new Reader(bytes);
  const value = reader.value();
  if (reader.consumed !== bytes.byteLength) {
    throw new MsgpackError(
      `trailing bytes: consumed ${reader.consumed} of ${bytes.byteLength}`,
    );
  }
  return value;
}

/** The decoded value as a string-keyed map, or null when it is not one. */
export function asMsgpackMap(
  value: MsgpackValue,
): { [key: string]: MsgpackValue } | null {
  return typeof value === "object" &&
    value !== null &&
    !Array.isArray(value) &&
    !(value instanceof Uint8Array)
    ? value
    : null;
}
