/**
 * @module agent/local-pair/types
 * @description Result + payload shapes for the local-first pair flow.
 * Pure type declarations — no runtime code, so every consumer keeps a
 * stable import surface through the barrel at `../local-pair-client`.
 * @license GPL-3.0-only
 */

export interface AgentBindState {
  state?: string | null;
  phase?: string | null;
  active: boolean;
  error?: string | null;
  finishedAt?: number | null;
  fingerprint?: string | null;
}

export interface AgentRadioSnapshot {
  state?: string | null;
  rssiDbm?: number | null;
  packetsReceived?: number | null;
}

export interface ProbeResult {
  deviceId: string;
  name: string;
  version: string;
  board: string;
  /** Cloud-pair status: the agent is claimed by a Mission Control
   * account via the Convex API-key flow. Distinct from `radioPaired`. */
  paired: boolean;
  /** Radio-pair status: the wfb-ng key handshake with the peer has
   * completed and the WFB radio link is authenticated. The two
   * states are independent — a cloud-paired drone may have no
   * radio pair, and a radio-paired drone may have no cloud claim. */
  radioPaired?: boolean;
  /** Truncated device-id of the radio-paired peer (16 ASCII chars).
   * Populated from the persisted pair state once bind completes or
   * a WFB-radio presence beacon back-fills it. */
  radioPeerDeviceId?: string | null;
  pairingCode?: string;
  ownerId?: string;
  pairedAt?: number;
  mdnsHost: string;
  profile: "drone" | "ground-station" | "workstation";
  role?: "direct" | "relay" | "receiver" | null;
  /** The normalised base URL the GCS should keep talking to. */
  hostname: string;
  /** Server-resolved IPv4 hint. Available when the probe route's
   * DNS lookup succeeded (mDNS names resolve here even if the
   * browser cannot resolve them). Used as a fallback when the
   * stored hostname later stops resolving from the renderer. */
  ipv4?: string;
  /** Live radio bind progress from the agent's pairing/info response.
   * Present once the agent exposes the bind state machine; undefined
   * for older agents that predate the field. */
  bindState?: AgentBindState;
  /** Snapshot of the radio link state at probe time (link state,
   * signal strength, packet count). Undefined for agents that don't
   * advertise it. */
  radio?: AgentRadioSnapshot;
}

export interface ClaimResult {
  apiKey: string;
  deviceId: string;
  name: string;
  mdnsHost: string;
  hostname: string;
}

/** Result shape mirrored from the agent's beacon registration in
 *  Convex. Used by `probeByCode` to resolve a 6-char code to the
 *  agent's LAN address.
 *
 *  NO apiKey. The relay never hands an agent credential to an anonymous
 *  caller: a six-character code is too weak a bearer to be exchangeable for
 *  one. The durable key is generated by the agent's own `/api/pairing/claim`
 *  on the actual claim call, which `probeByCode` chains into through
 *  `probeAgent` → `pairLocally`, and which only a caller with LAN reach to the
 *  agent can complete.
 */
// The claim mutation returns an expected-failure result instead of throwing,
// so a code the relay does not know produces no console error. Discriminate
// on `error`: a set string is the failure, null/absent is the success payload.
export type CodeClaimResult =
  | {
      error:
        | "invalid_pairing_code"
        | "pairing_code_expired"
        | "code_already_claimed"
        | "device_owned_by_other"
        | "invalid_browser_session";
    }
  | {
      error?: null;
      deviceId: string;
      name: string;
      mdnsHost?: string;
      localIp?: string;
      board?: string;
      agentVersion?: string;
    };
