//! Generation of the self-host config files — the `tools/selfhost/.env` and the
//! `docker-compose.override.yml` (only when ports are remapped).
//!
//! The content builders are pure (they feed both the `--plan` preview and the
//! real write). Secrets only ever land in these gitignored files; `.env`
//! carries the instance secret + MQTT password, and the write path refuses to
//! write to a path git does not ignore.

use std::path::Path;

use crate::services::{self, Ports};
use crate::wizard::state::DeployConfig;

/// Render the `tools/selfhost/.env` content for `cfg`. Matches the keys the
/// compose file + the MQTT bridge read.
pub fn render_env(cfg: &DeployConfig) -> String {
    let mut out = String::new();
    out.push_str("# Generated by ados-deploy. Contains secrets — never commit (gitignored).\n");
    out.push_str("# Re-run `ados-deploy` to regenerate.\n\n");

    out.push_str("# --- Convex backend identity (pins the deterministic admin key) ---\n");
    kv(&mut out, "CONVEX_INSTANCE_NAME", &cfg.instance_name);
    kv(&mut out, "CONVEX_INSTANCE_SECRET", &cfg.instance_secret);
    kv(&mut out, "CONVEX_CLOUD_ORIGIN", &cfg.convex_cloud_origin());
    kv(&mut out, "CONVEX_SITE_ORIGIN", &cfg.convex_site_origin());
    out.push('\n');

    out.push_str("# --- URLs the browser + agents use ---\n");
    out.push_str("# Baked into the Mission Control image at build time.\n");
    kv(
        &mut out,
        "NEXT_PUBLIC_CONVEX_URL",
        &cfg.next_public_convex_url(),
    );
    out.push_str("# The agent heartbeat + MQTT bridge POST here (Convex site origin).\n");
    kv(&mut out, "CONVEX_URL", &cfg.convex_site_url());
    out.push('\n');

    out.push_str("# --- MQTT principals ---\n");
    kv(&mut out, "MQTT_USERNAME", &cfg.mqtt_username);
    kv(&mut out, "MQTT_PASSWORD", &cfg.mqtt_password);
    out.push('\n');

    out.push_str("# --- Video relay ---\n");
    kv(
        &mut out,
        "RTSP_URL_PATTERN",
        "rtsp://host.docker.internal:8554/{deviceId}",
    );
    out
}

/// Render a `docker-compose.override.yml` remapping host ports, or `None` when
/// every port is the compose default (no override needed).
pub fn render_override(cfg: &DeployConfig) -> Option<String> {
    if cfg.ports.is_default() {
        return None;
    }
    let p = &cfg.ports;
    let mut out = String::new();
    out.push_str("# Generated by ados-deploy — host port remaps.\n");
    out.push_str("services:\n");
    // Each entry: (compose service, [(host, container)]).
    let mut svc = |name: &str, maps: &[(u16, u16)]| {
        out.push_str(&format!("  {name}:\n    ports:\n"));
        for (host, container) in maps {
            out.push_str(&format!("      - \"{host}:{container}\"\n"));
        }
    };
    if !cfg.convex.is_managed() {
        svc(
            services::SVC_CONVEX_BACKEND,
            &[(p.convex_client, 3210), (p.convex_site, 3211)],
        );
        svc(services::SVC_CONVEX_DASHBOARD, &[(p.dashboard, 6791)]);
    }
    if cfg.gcs {
        svc(services::SVC_MISSION_CONTROL, &[(p.gcs, 4000)]);
    }
    if !cfg.mqtt.is_managed() {
        svc(
            services::SVC_MOSQUITTO,
            &[(p.mqtt_tcp, 1883), (p.mqtt_ws, 9001)],
        );
    }
    if !cfg.video.is_managed() {
        svc(services::SVC_VIDEO_RELAY, &[(p.video, 3001)]);
    }
    Some(out)
}

/// The Convex environment variables set (out of band, via `npx convex env set`)
/// after functions are deployed. `JWT_PRIVATE_KEY` / `JWKS` are generated at
/// deploy time; the returned list is the (name, value) pairs derivable from
/// `cfg` (the auth keys are added by the deploy step, not here).
pub fn convex_env_vars(cfg: &DeployConfig) -> Vec<(&'static str, String)> {
    let mut v = vec![("SITE_URL", cfg.site_url())];
    // Advertise a relay URL only when there is a real one. A service disabled via
    // `--no-mqtt`/`--no-video` is `Managed { url: "" }`, which must NOT push an
    // empty MQTT_BROKER_URL / VIDEO_RELAY_URL onto Convex (C10/C11).
    let broker = cfg.mqtt_broker_url();
    if !broker.is_empty() {
        v.push(("MQTT_BROKER_URL", broker));
    }
    let relay = cfg.video_relay_url();
    if !relay.is_empty() {
        v.push(("VIDEO_RELAY_URL", relay));
    }
    v
}

fn kv(out: &mut String, key: &str, value: &str) {
    out.push_str(&format!("{key}={value}\n"));
}

/// Read one `KEY=value` from the generated `tools/selfhost/.env` (trimmed,
/// non-empty), or `None` if the file or key is absent.
pub fn read_env_var(repo_root: &Path, key: &str) -> Option<String> {
    let text = std::fs::read_to_string(repo_root.join("tools/selfhost/.env")).ok()?;
    text.lines()
        .find_map(|l| l.strip_prefix(&format!("{key}=")))
        .map(|v| v.trim().to_string())
        .filter(|v| !v.is_empty())
}

/// Read the generated instance secret + MQTT password from an existing
/// `tools/selfhost/.env`, so a re-run reuses them instead of minting new ones.
/// This keeps the deploy idempotent: the Convex admin key is derived from the
/// instance secret, so a stable secret means a re-run/upgrade targets the same
/// backend and never needlessly recreates the container.
pub fn read_existing_secrets(repo_root: &Path) -> Option<(String, String)> {
    Some((
        read_env_var(repo_root, "CONVEX_INSTANCE_SECRET")?,
        read_env_var(repo_root, "MQTT_PASSWORD")?,
    ))
}

/// Recover the host-facing ports from an existing `docker-compose.override.yml`
/// (the only place custom ports are recorded). Maps each `"<host>:<container>"`
/// entry back onto its port field by the fixed container port; absent file or
/// unremapped ports keep the compose defaults. Used by `config_from_env` so an
/// upgrade/reconfigure targets the same ports a custom-port deploy chose.
pub fn read_existing_ports(repo_root: &Path) -> Ports {
    let mut p = Ports::default();
    let Ok(text) =
        std::fs::read_to_string(repo_root.join("tools/selfhost/docker-compose.override.yml"))
    else {
        return p;
    };
    for line in text.lines() {
        let line = line.trim();
        let Some(rest) = line.strip_prefix("- ") else {
            continue;
        };
        let rest = rest.trim().trim_matches('"');
        let Some((host_s, container_s)) = rest.split_once(':') else {
            continue;
        };
        let (Ok(host), Ok(container)) = (host_s.parse::<u16>(), container_s.parse::<u16>()) else {
            continue;
        };
        match container {
            3210 => p.convex_client = host,
            3211 => p.convex_site = host,
            6791 => p.dashboard = host,
            4000 => p.gcs = host,
            1883 => p.mqtt_tcp = host,
            9001 => p.mqtt_ws = host,
            3001 => p.video = host,
            _ => {}
        }
    }
    p
}

/// Whether git ignores `path` (so a secret written there is never committed).
/// Runs `git check-ignore -q` relative to the repo the path lives in.
pub fn is_gitignored(repo_root: &Path, path: &Path) -> bool {
    std::process::Command::new("git")
        .arg("check-ignore")
        .arg("-q")
        .arg(path)
        .current_dir(repo_root)
        .status()
        .map(|s| s.success())
        .unwrap_or(false)
}

/// Write secret content to a gitignored path, creating parent dirs and setting
/// owner-only permissions (0600) on unix. Refuses if git does not ignore the
/// path (a guard against ever committing a secret).
pub fn write_secret_file(repo_root: &Path, path: &Path, content: &str) -> anyhow::Result<()> {
    if !is_gitignored(repo_root, path) {
        anyhow::bail!(
            "refusing to write a secret to {} — it is not gitignored (add it to .gitignore first)",
            path.display()
        );
    }
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(path, content)?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let _ = std::fs::set_permissions(path, std::fs::Permissions::from_mode(0o600));
    }
    Ok(())
}

#[cfg(test)]
#[allow(clippy::field_reassign_with_default)]
mod tests {
    use super::*;
    use crate::wizard::state::Provision;

    fn cfg() -> DeployConfig {
        let mut c = DeployConfig::default();
        c.host = "192.168.1.50".to_string();
        c.instance_name = "ados-selfhosted".to_string();
        c.instance_secret = "aabbcc".to_string();
        c.mqtt_password = "secretpw".to_string();
        c
    }

    #[test]
    fn env_has_required_keys() {
        let e = render_env(&cfg());
        for k in [
            "CONVEX_INSTANCE_NAME=ados-selfhosted",
            "CONVEX_INSTANCE_SECRET=aabbcc",
            "NEXT_PUBLIC_CONVEX_URL=http://192.168.1.50:3210",
            "CONVEX_URL=http://192.168.1.50:3211",
            "MQTT_USERNAME=ados",
            "MQTT_PASSWORD=secretpw",
            "RTSP_URL_PATTERN=rtsp://host.docker.internal:8554/{deviceId}",
        ] {
            assert!(e.contains(k), "env missing {k}\n---\n{e}");
        }
    }

    #[test]
    fn default_ports_need_no_override() {
        assert!(render_override(&cfg()).is_none());
    }

    #[test]
    fn remapped_port_produces_override() {
        let mut c = cfg();
        c.ports.gcs = 8080;
        let ov = render_override(&c).expect("override for remapped port");
        assert!(ov.contains("mission-control:"));
        assert!(ov.contains("\"8080:4000\""));
    }

    #[test]
    fn managed_convex_omits_backend_from_override() {
        let mut c = cfg();
        c.ports.gcs = 8080;
        c.convex = Provision::Managed {
            url: "https://convex.example.com".to_string(),
        };
        let ov = render_override(&c).unwrap();
        assert!(!ov.contains("convex-backend:"));
        assert!(ov.contains("mission-control:"));
    }

    #[test]
    fn read_existing_secrets_and_vars_round_trip() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        let sh = root.join("tools/selfhost");
        std::fs::create_dir_all(&sh).unwrap();
        std::fs::write(
            sh.join(".env"),
            "CONVEX_INSTANCE_SECRET=deadbeef\nMQTT_PASSWORD=hunter2\nEMPTY=\nOTHER=x\n",
        )
        .unwrap();
        assert_eq!(
            read_existing_secrets(root),
            Some(("deadbeef".to_string(), "hunter2".to_string()))
        );
        assert_eq!(read_env_var(root, "OTHER").as_deref(), Some("x"));
        assert!(read_env_var(root, "EMPTY").is_none()); // blank value → None
        assert!(read_env_var(root, "NOPE").is_none());
    }

    #[test]
    fn read_existing_ports_recovers_remaps_and_keeps_defaults() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        let sh = root.join("tools/selfhost");
        std::fs::create_dir_all(&sh).unwrap();
        // No override on disk → the compose defaults.
        assert_eq!(read_existing_ports(root), Ports::default());
        // An override remapping two ports round-trips; the rest stay default.
        let mut c = cfg();
        c.ports.gcs = 8080;
        c.ports.convex_client = 13210;
        let ov = render_override(&c).unwrap();
        std::fs::write(sh.join("docker-compose.override.yml"), ov).unwrap();
        let p = read_existing_ports(root);
        assert_eq!(p.gcs, 8080);
        assert_eq!(p.convex_client, 13210);
        assert_eq!(p.convex_site, Ports::default().convex_site);
    }
}
