/**
 * Broker password-file entry generation.
 *
 * The load-bearing test is the captured vector: an entry produced by the
 * broker's own tool, checked against our Web Crypto derivation. If the
 * parameters ever drift — iteration count, digest, salt handling, base64
 * padding — every credential we mint is refused by the broker, and the only
 * evidence is a denial in the broker's log. That failure is invisible from the
 * application side, which is exactly why the agreement is pinned here rather
 * than assumed from the format's shape.
 *
 * The vector below was generated locally by the broker's own `mosquitto_passwd`
 * against a throwaway user, and a fresh entry built by this module was then
 * confirmed to authenticate a real broker (and a wrong secret confirmed to be
 * rejected). Nothing here is a live credential.
 */
import { describe, expect, it } from "vitest";

import {
  MOSQUITTO_HASH_BYTES,
  MOSQUITTO_PBKDF2_ITERATIONS,
  MOSQUITTO_SALT_BYTES,
  buildPasswdEntry,
  verifyPasswdEntry,
} from "../../convex/mosquittoPasswd";

/** Captured from `mosquitto_passwd -b`. Throwaway user, throwaway secret. */
const CAPTURED_ENTRY =
  "testuser:$7$1000$NmvqwWu9BBG8N85HITzkcKgQ3LiqWcFoo13Bvu8YcFFHqIvfgLUIVm2QHU3Hn4MhbuWnAfcsU2iYt5m15CsiDQ==$6OW0Sx0Iu6gOwm9LBlQ0dfVeBMH9NGlx5qyW5wI56Ls30VIKB9nH5RS9zFKgQX5hcGi79U+7Wsg/hA+9j7h5nw==";
const CAPTURED_SECRET = "hunter2correct";

describe("mosquitto passwd entry", () => {
  it("reproduces an entry generated by the broker's own tool", async () => {
    // The whole point: our derivation and the broker's agree on a real sample.
    await expect(
      verifyPasswdEntry(CAPTURED_ENTRY, CAPTURED_SECRET),
    ).resolves.toBe(true);
  });

  it("rejects the wrong secret against that same entry", async () => {
    await expect(
      verifyPasswdEntry(CAPTURED_ENTRY, "hunter2correct "),
    ).resolves.toBe(false);
    await expect(verifyPasswdEntry(CAPTURED_ENTRY, "")).resolves.toBe(false);
  });

  it("emits the parameters the broker's tool writes", () => {
    const rest = CAPTURED_ENTRY.slice(CAPTURED_ENTRY.indexOf(":") + 1);
    const parts = rest.split("$");
    expect(parts[1]).toBe("7");
    expect(Number(parts[2])).toBe(MOSQUITTO_PBKDF2_ITERATIONS);
    expect(atob(parts[3]).length).toBe(MOSQUITTO_SALT_BYTES);
    expect(atob(parts[4]).length).toBe(MOSQUITTO_HASH_BYTES);
  });

  it("round-trips an entry it generated itself", async () => {
    const entry = await buildPasswdEntry("gcs-op-example", "a-minted-secret");
    expect(entry.startsWith("gcs-op-example:$7$1000$")).toBe(true);
    await expect(verifyPasswdEntry(entry, "a-minted-secret")).resolves.toBe(
      true,
    );
    await expect(verifyPasswdEntry(entry, "a-minted-secre")).resolves.toBe(
      false,
    );
  });

  it("salts every entry separately", async () => {
    // Two entries for one secret must differ, or the file leaks which
    // principals share a credential.
    const a = await buildPasswdEntry("gcs-op-a", "same-secret");
    const b = await buildPasswdEntry("gcs-op-b", "same-secret");
    expect(a.split("$")[3]).not.toBe(b.split("$")[3]);
    expect(a.split("$")[4]).not.toBe(b.split("$")[4]);
  });

  it("refuses a username that would forge a second entry", async () => {
    // The file is line- and colon-delimited; either character in a username
    // would let one entry masquerade as two.
    await expect(buildPasswdEntry("evil:user", "x")).rejects.toThrow();
    await expect(buildPasswdEntry("evil\nuser", "x")).rejects.toThrow();
  });

  it("rejects a malformed entry rather than reading it as a match", async () => {
    for (const bad of [
      "",
      "nocolon",
      "user:notadollarformat",
      "user:$6$1000$c2FsdA==$aGFzaA==", // wrong scheme
      "user:$7$0$c2FsdA==$aGFzaA==", // nonsense iteration count
      "user:$7$1000$c2FsdA==", // truncated
    ]) {
      await expect(verifyPasswdEntry(bad, "x")).resolves.toBe(false);
    }
  });
});
