#!/usr/bin/env bash
# Regenerate /opt/relay/mosquitto/passwd and /opt/relay/mosquitto/acl.conf
# from paired devices in Convex.
#
# Reads CONVEX_HTTP_URL, MQTT_AUTH_RELAY_SECRET, and BRIDGE_MQTT_PASSWORD
# (or MQTT_PASSWORD) from the broker host's environment (typically
# /opt/relay/.env). Pulls the device_id / apiKey pair list from the
# /admin/mqtt-auth-entries httpAction (Bearer-token gated by
# MQTT_AUTH_RELAY_SECRET) and rebuilds both files, then SIGHUPs the broker.
#
# Writes BOTH username conventions per device:
#   - <device_id>            (canonical; agents on current firmware)
#   - ados-<device_id>       (legacy; bench drones still on old firmware)
# Both entries hash the same apiKey. Once all agents are upgraded to the
# canonical username, set DROP_LEGACY_USERNAMES=1 to stop emitting the
# `ados-<id>` rows.
#
# Also emits per-operator write grants, which is what lets a browser publish
# at all: the shared viewer principal is read-only by design.
#
# Safe to run from cron. Idempotent. Writes the two files IN PLACE (see the
# note by the write) because they are file-level bind mounts -- a rename would
# leave the broker reading the old inode and look like a working sync.
#
# PATHS AND CONTAINER NAME DEFAULT TO THE PRE-MIGRATION DEPLOYMENT. On the
# current host, override BROKER_CONTAINER / PASSWD_PATH / ACL_PATH (see
# regenerate-passwd.env next to this script). Defaults left alone so an older
# deployment is not silently repointed.

set -euo pipefail

CONVEX_HTTP_URL="${CONVEX_HTTP_URL:-https://convex.your-domain.com:3211}"
RELAY_SECRET="${MQTT_AUTH_RELAY_SECRET:-}"
BRIDGE_USER="${BRIDGE_MQTT_USERNAME:-ados}"
BRIDGE_PASS="${BRIDGE_MQTT_PASSWORD:-${MQTT_PASSWORD:-}}"
VIEWER_USER="${MQTT_VIEWER_USERNAME:-gcs-viewer}"
VIEWER_PASS="${MQTT_VIEWER_PASSWORD:-}"
PASSWD_PATH="${PASSWD_PATH:-/opt/relay/mosquitto/passwd}"
ACL_PATH="${ACL_PATH:-/opt/relay/mosquitto/acl.conf}"
BROKER_CONTAINER="${BROKER_CONTAINER:-relay-mosquitto-1}"
DROP_LEGACY_USERNAMES="${DROP_LEGACY_USERNAMES:-0}"

if [[ -z "${RELAY_SECRET}" ]]; then
  echo "regenerate-passwd: MQTT_AUTH_RELAY_SECRET not set; aborting" >&2
  exit 1
fi
if [[ -z "${BRIDGE_PASS}" ]]; then
  echo "regenerate-passwd: BRIDGE_MQTT_PASSWORD (or MQTT_PASSWORD) not set; aborting" >&2
  exit 1
fi
if [[ -z "${VIEWER_PASS}" ]]; then
  echo "regenerate-passwd: MQTT_VIEWER_PASSWORD not set; aborting" >&2
  exit 1
fi

response=$(curl -fsS \
  -H "Authorization: Bearer ${RELAY_SECRET}" \
  "${CONVEX_HTTP_URL}/admin/mqtt-auth-entries")

entries_count=$(printf '%s' "${response}" | jq -r '.entries | length')
if [[ -z "${entries_count}" || "${entries_count}" == "null" ]]; then
  echo "regenerate-passwd: malformed response from Convex: ${response}" >&2
  exit 1
fi

# The Convex query is bounded, and reports when it hit its cap. A truncated
# payload means the tail of the estate is missing from the file about to be
# written, and the broker's only symptom is "those devices cannot connect" --
# a silent partial sync is worse than a failed one, so refuse to write.
truncated=$(printf '%s' "${response}" | jq -r '.truncated // false')
if [[ "${truncated}" == "true" ]]; then
  echo "regenerate-passwd: Convex truncated the auth payload at its cap;" >&2
  echo "  refusing to write a partial passwd/ACL. Raise MAX_MQTT_AUTH_ENTRIES" >&2
  echo "  in convex/cmdPairing.ts (both twins) and redeploy." >&2
  exit 1
fi

# Build passwd inside the broker container at a staging path.
STAGING_PASSWD="/tmp/.mqtt-passwd-stage"
docker exec "${BROKER_CONTAINER}" sh -c \
  "rm -f '${STAGING_PASSWD}' && touch '${STAGING_PASSWD}' && chmod 600 '${STAGING_PASSWD}'"

# Build acl.conf on the host (no mosquitto-specific tooling needed for ACL).
host_acl_staging="$(mktemp --tmpdir mqtt-acl.XXXXXX)"
chmod 644 "${host_acl_staging}"

cat > "${host_acl_staging}" <<'ACL_HEADER'
# Mosquitto ACL for the ADOS cloud relay.
#
# AUTO-GENERATED by regenerate-passwd.sh. Do not edit by hand; changes will
# be overwritten on the next sync. The static `acl.conf` shipped in the
# ADOSMissionControl repo at tools/mqtt-bridge/deploy/acl.conf is the
# documented policy; this file is the materialized per-device version.
#
# Format per device:
#   user <username>
#   topic readwrite ados/<device_id>/#
#
# Username is either the bare device_id (current firmware) or
# `ados-<device_id>` (legacy firmware); both grant the same topic subtree.

ACL_HEADER

# Bridge service account: read-only across all `ados/+/...` topics.
cat >> "${host_acl_staging}" <<ACL_BRIDGE
user ${BRIDGE_USER}
topic read ados/#

# Legacy shared viewer: read-only across every `ados/...` topic. No browser reads
# it any more -- a Mission Control session authenticates with the operator's own
# minted write grant (below), scoped to the devices they own. This principal
# survives only for a deployment still serving a build that predates that path.
# Protect telemetry beyond this via TLS + Cloudflare Tunnel; do NOT grant write
# access here.
user ${VIEWER_USER}
topic read ados/#

ACL_BRIDGE

# Iterate device list, write to both passwd (via mosquitto_passwd inside
# container) and acl.conf (plain text on host).
printf '%s' "${response}" \
  | jq -r '.entries[] | "\(.username)\t\(.apiKey)"' \
  | while IFS=$'\t' read -r device_id apikey; do
      [[ -z "${device_id}" || -z "${apikey}" ]] && continue

      # passwd: canonical username == device_id
      docker exec "${BROKER_CONTAINER}" \
        mosquitto_passwd -b "${STAGING_PASSWD}" "${device_id}" "${apikey}"

      # acl.conf: canonical
      cat >> "${host_acl_staging}" <<ACL_DEVICE
user ${device_id}
topic readwrite ados/${device_id}/#

ACL_DEVICE

      if [[ "${DROP_LEGACY_USERNAMES}" != "1" ]]; then
        # passwd: legacy ados-<device_id>
        docker exec "${BROKER_CONTAINER}" \
          mosquitto_passwd -b "${STAGING_PASSWD}" "ados-${device_id}" "${apikey}"

        # acl.conf: legacy, same topic subtree
        cat >> "${host_acl_staging}" <<ACL_LEGACY
user ados-${device_id}
topic readwrite ados/${device_id}/#

ACL_LEGACY
      fi
    done

# Operator write grants.
#
# The shared viewer principal is read-only by design, so a browser has never
# been able to publish a command -- flight frames and video signalling were
# accepted by the client and then discarded by the broker. A grant is what
# gives one operator write access, scoped to the devices they owned when it
# was minted, and it expires on its own.
#
# `passwdEntry` is already a broker password line (a PBKDF2 verifier, never the
# secret), so it is appended verbatim rather than re-hashed -- the plaintext
# never reaches this host. Convex has already dropped expired and revoked
# grants, so everything here is live.
grants_count=$(printf '%s' "${response}" | jq -r '(.grants // []) | length')
if [[ "${grants_count}" != "0" ]]; then
  printf '%s' "${response}" \
    | jq -r '(.grants // [])[] | "\(.principal)\t\(.passwdEntry)\t\(.deviceIds | join(","))"' \
    | while IFS=$'\t' read -r principal passwd_entry device_csv; do
        [[ -z "${principal}" || -z "${passwd_entry}" ]] && continue

        # passwd: append the pre-hashed verifier straight into the staging file.
        docker exec -i "${BROKER_CONTAINER}" \
          sh -c "cat >> '${STAGING_PASSWD}'" <<< "${passwd_entry}"

        {
          echo "# Operator grant. Expires on its own; revoking in Convex drops"
          echo "# it from the next sync."
          echo "user ${principal}"
          IFS=',' read -ra _devs <<< "${device_csv}"
          for d in "${_devs[@]}"; do
            [[ -n "${d}" ]] && echo "topic readwrite ados/${d}/#"
          done
          echo ""
        } >> "${host_acl_staging}"
      done
fi

# Bridge service account in passwd.
docker exec "${BROKER_CONTAINER}" \
  mosquitto_passwd -b "${STAGING_PASSWD}" "${BRIDGE_USER}" "${BRIDGE_PASS}"

# GCS viewer service account in passwd.
docker exec "${BROKER_CONTAINER}" \
  mosquitto_passwd -b "${STAGING_PASSWD}" "${VIEWER_USER}" "${VIEWER_PASS}"

# Copy passwd out of container, atomic-rename into place on host.
host_passwd_staging="$(mktemp --tmpdir mqtt-passwd.XXXXXX)"
chmod 600 "${host_passwd_staging}"
docker exec "${BROKER_CONTAINER}" /bin/cat "${STAGING_PASSWD}" > "${host_passwd_staging}"
docker exec "${BROKER_CONTAINER}" rm -f "${STAGING_PASSWD}"

# Write IN PLACE, never rename.
#
# These paths are FILE-level bind mounts into the broker container. A rename
# gives the host path a NEW inode while the container keeps the old one, so
# `mv` would report success and the broker would go on reading the previous
# file forever -- a silent no-op that looks like a working sync. Truncating and
# rewriting keeps the inode, so the container sees the new bytes.
#
# The cost is that the write is no longer atomic. That is acceptable here: the
# broker only re-reads on the SIGHUP below, so it never observes a partial file
# in normal operation.
cat "${host_passwd_staging}" > "${PASSWD_PATH}"
rm -f "${host_passwd_staging}"
# Mosquitto inside the container runs as uid 1883; the host-side file must
# be readable by that uid. 640 means owner-read/group-read, others-none.
chown 1883:1883 "${PASSWD_PATH}"
chmod 640 "${PASSWD_PATH}"

cat "${host_acl_staging}" > "${ACL_PATH}"
rm -f "${host_acl_staging}"
chown 1883:1883 "${ACL_PATH}"
chmod 640 "${ACL_PATH}"

# Reload the broker without dropping connections.
docker exec "${BROKER_CONTAINER}" sh -c 'kill -HUP 1' 2>/dev/null || true

echo "regenerate-passwd: wrote ${PASSWD_PATH} + ${ACL_PATH} (${entries_count} devices, ${grants_count:-0} operator grants, + bridge + viewer)"
