#!/usr/bin/env bash
# Regenerate /opt/relay/mosquitto/passwd and /opt/relay/mosquitto/acl.conf
# from paired devices in Convex.
#
# Reads CONVEX_HTTP_URL, MQTT_AUTH_RELAY_SECRET, and BRIDGE_MQTT_PASSWORD
# (or MQTT_PASSWORD) from the broker host's environment (typically
# /opt/relay/.env). Pulls the device_id / apiKey pair list from the
# /admin/mqtt-auth-entries httpAction (Bearer-token gated by
# MQTT_AUTH_RELAY_SECRET) and rebuilds both files, then SIGHUPs the broker.
#
# Writes one passwd row per device under the username the agent presents,
# `ados-<device_id>`, with the device's apiKey as the password, and an ACL
# entry granting that user its own `ados/<device_id>/#` subtree.
#
# Also emits per-operator write grants, which is what lets a browser publish
# at all: each grant may read its devices' subtrees and write only the three
# topics a GCS sends on.
#
# Safe to run from cron. Idempotent. Writes the two files IN PLACE (see the
# note by the write) because they are file-level bind mounts -- a rename would
# leave the broker reading the old inode and look like a working sync.
#
# PATHS AND CONTAINER NAME DEFAULT TO THE PRE-MIGRATION DEPLOYMENT. On the
# current host, override BROKER_CONTAINER / PASSWD_PATH / ACL_PATH (see
# regenerate-passwd.env next to this script). Defaults left alone so an older
# deployment is not silently repointed.
#
# BROKER_CONTAINER=local runs every broker-side step in THIS container instead
# of through `docker exec`: mosquitto_passwd must be on PATH, and the broker
# must share this container's PID namespace so the final SIGHUP reaches it.
# That is how the self-host stack's `mqtt-auth-sync` sidecar runs the script
# (tools/selfhost/docker-compose.yml): no docker socket is mounted anywhere.

set -euo pipefail

CONVEX_HTTP_URL="${CONVEX_HTTP_URL:-https://convex.your-domain.com:3211}"
RELAY_SECRET="${MQTT_AUTH_RELAY_SECRET:-}"
BRIDGE_USER="${BRIDGE_MQTT_USERNAME:-ados}"
BRIDGE_PASS="${BRIDGE_MQTT_PASSWORD:-${MQTT_PASSWORD:-}}"
PASSWD_PATH="${PASSWD_PATH:-/opt/relay/mosquitto/passwd}"
ACL_PATH="${ACL_PATH:-/opt/relay/mosquitto/acl.conf}"
BROKER_CONTAINER="${BROKER_CONTAINER:-relay-mosquitto-1}"

# Run a command where the broker's tools live: this container, or the broker's.
if [[ "${BROKER_CONTAINER}" == "local" ]]; then
  in_broker() { "$@"; }
  in_broker_stdin() { "$@"; }
  reload_broker() {
    local pid
    pid="$(pidof mosquitto || true)"
    if [[ -z "${pid}" ]]; then
      echo "regenerate-passwd: no mosquitto process in this PID namespace; not reloaded" >&2
      return 1
    fi
    kill -HUP ${pid}
  }
else
  in_broker() { docker exec "${BROKER_CONTAINER}" "$@"; }
  in_broker_stdin() { docker exec -i "${BROKER_CONTAINER}" "$@"; }
  reload_broker() { docker exec "${BROKER_CONTAINER}" sh -c 'kill -HUP 1' 2>/dev/null || true; }
fi

if [[ -z "${RELAY_SECRET}" ]]; then
  echo "regenerate-passwd: MQTT_AUTH_RELAY_SECRET not set; aborting" >&2
  exit 1
fi
if [[ -z "${BRIDGE_PASS}" ]]; then
  echo "regenerate-passwd: BRIDGE_MQTT_PASSWORD (or MQTT_PASSWORD) not set; aborting" >&2
  exit 1
fi

response=$(curl -fsS \
  -H "Authorization: Bearer ${RELAY_SECRET}" \
  "${CONVEX_HTTP_URL}/admin/mqtt-auth-entries")

entries_count=$(printf '%s' "${response}" | jq -r '.entries | length')
if [[ -z "${entries_count}" || "${entries_count}" == "null" ]]; then
  echo "regenerate-passwd: malformed response from Convex: ${response}" >&2
  exit 1
fi

# The Convex query is bounded, and reports when it hit its cap. A truncated
# payload means the tail of the estate is missing from the file about to be
# written, and the broker's only symptom is "those devices cannot connect" --
# a silent partial sync is worse than a failed one, so refuse to write.
truncated=$(printf '%s' "${response}" | jq -r '.truncated // false')
if [[ "${truncated}" == "true" ]]; then
  echo "regenerate-passwd: Convex truncated the auth payload at its cap;" >&2
  echo "  refusing to write a partial passwd/ACL. Raise MAX_MQTT_AUTH_ENTRIES" >&2
  echo "  in convex/cmdPairing.ts (both twins) and redeploy." >&2
  exit 1
fi

# Build passwd inside the broker container at a staging path.
STAGING_PASSWD="/tmp/.mqtt-passwd-stage"
in_broker sh -c \
  "rm -f '${STAGING_PASSWD}' && touch '${STAGING_PASSWD}' && chmod 600 '${STAGING_PASSWD}'"

# Build acl.conf on the host (no mosquitto-specific tooling needed for ACL).
host_acl_staging="$(mktemp --tmpdir mqtt-acl.XXXXXX)"
chmod 644 "${host_acl_staging}"

cat > "${host_acl_staging}" <<'ACL_HEADER'
# Mosquitto ACL for the ADOS cloud relay.
#
# AUTO-GENERATED by regenerate-passwd.sh. Do not edit by hand; changes will
# be overwritten on the next sync. The static `acl.conf` shipped in the
# ADOSMissionControl repo at tools/mqtt-bridge/deploy/acl.conf is the
# documented policy; this file is the materialized per-device version.
#
# Format per device (the agent's MQTT username is `ados-<device_id>`):
#   user ados-<device_id>
#   topic readwrite ados/<device_id>/#
#
# Format per operator grant:
#   user gcs-op-<random>
#   topic read  ados/<device_id>/#
#   topic write ados/<device_id>/mavlink/rx
#   topic write ados/<device_id>/msp/rx
#   topic write ados/<device_id>/webrtc/offer

ACL_HEADER

# Bridge service account: read-only across all `ados/+/...` topics.
cat >> "${host_acl_staging}" <<ACL_BRIDGE
user ${BRIDGE_USER}
topic read ados/#

ACL_BRIDGE

# Iterate device list, write to both passwd (via mosquitto_passwd inside
# container) and acl.conf (plain text on host). The entry's `username` field
# is the device id; the broker principal is the name the agent logs in with.
printf '%s' "${response}" \
  | jq -r '.entries[] | "\(.username)\t\(.apiKey)"' \
  | while IFS=$'\t' read -r device_id apikey; do
      [[ -z "${device_id}" || -z "${apikey}" ]] && continue

      in_broker \
        mosquitto_passwd -b "${STAGING_PASSWD}" "ados-${device_id}" "${apikey}"

      cat >> "${host_acl_staging}" <<ACL_DEVICE
user ados-${device_id}
topic readwrite ados/${device_id}/#

ACL_DEVICE
    done

# Operator write grants.
#
# A grant is what gives one operator write access, scoped to the devices they
# owned when it was minted, and it expires on its own. Write is limited to the
# three topics a GCS sends on: the whole subtree would also let the holder
# publish `/tx`, `/status` and `/webrtc/answer` -- the agent's own topics -- and
# so fabricate telemetry for the aircraft.
#
# `passwdEntry` is already a broker password line (a PBKDF2 verifier, never the
# secret), so it is appended verbatim rather than re-hashed -- the plaintext
# never reaches this host. Convex has already dropped expired and revoked
# grants, so everything here is live.
grants_count=$(printf '%s' "${response}" | jq -r '(.grants // []) | length')
if [[ "${grants_count}" != "0" ]]; then
  printf '%s' "${response}" \
    | jq -r '(.grants // [])[] | "\(.principal)\t\(.passwdEntry)\t\(.deviceIds | join(","))"' \
    | while IFS=$'\t' read -r principal passwd_entry device_csv; do
        [[ -z "${principal}" || -z "${passwd_entry}" ]] && continue

        # passwd: append the pre-hashed verifier straight into the staging file.
        in_broker_stdin \
          sh -c "cat >> '${STAGING_PASSWD}'" <<< "${passwd_entry}"

        {
          echo "# Operator grant. Expires on its own; revoking in Convex drops"
          echo "# it from the next sync."
          echo "user ${principal}"
          IFS=',' read -ra _devs <<< "${device_csv}"
          for d in "${_devs[@]}"; do
            [[ -z "${d}" ]] && continue
            echo "topic read ados/${d}/#"
            echo "topic write ados/${d}/mavlink/rx"
            echo "topic write ados/${d}/msp/rx"
            echo "topic write ados/${d}/webrtc/offer"
          done
          echo ""
        } >> "${host_acl_staging}"
      done
fi

# Bridge service account in passwd.
in_broker \
  mosquitto_passwd -b "${STAGING_PASSWD}" "${BRIDGE_USER}" "${BRIDGE_PASS}"

# Copy passwd out of the container into a host staging file.
host_passwd_staging="$(mktemp --tmpdir mqtt-passwd.XXXXXX)"
chmod 600 "${host_passwd_staging}"
in_broker /bin/cat "${STAGING_PASSWD}" > "${host_passwd_staging}"
in_broker rm -f "${STAGING_PASSWD}"

# Write IN PLACE, never rename.
#
# These paths are FILE-level bind mounts into the broker container. A rename
# gives the host path a NEW inode while the container keeps the old one, so
# `mv` would report success and the broker would go on reading the previous
# file forever -- a silent no-op that looks like a working sync. Truncating and
# rewriting keeps the inode, so the container sees the new bytes.
#
# The cost is that the write is no longer atomic. That is acceptable here: the
# broker only re-reads on the SIGHUP below, so it never observes a partial file
# in normal operation.
cat "${host_passwd_staging}" > "${PASSWD_PATH}"
rm -f "${host_passwd_staging}"
# Mosquitto inside the container runs as uid 1883; the host-side file must
# be readable by that uid. 640 means owner-read/group-read, others-none.
chown 1883:1883 "${PASSWD_PATH}"
chmod 640 "${PASSWD_PATH}"

cat "${host_acl_staging}" > "${ACL_PATH}"
rm -f "${host_acl_staging}"
chown 1883:1883 "${ACL_PATH}"
chmod 640 "${ACL_PATH}"

# Reload the broker without dropping connections.
reload_broker

echo "regenerate-passwd: wrote ${PASSWD_PATH} + ${ACL_PATH} (${entries_count} devices, ${grants_count:-0} operator grants, + bridge)"
